name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache
      uses: actions/cache@v1.2.1
      with:
        # A directory to store and save the cache
        path: /cache
        # An explicit key for restoring and saving the cache
        key: caramell-cache
    - name: InstallDeps
      run: sudo apt install -y npm && npm install -g truffle && npm install --save @truffle/hdwallet-provider
    - name: InstallSubmods
      run: git submodule init && git submodule update
    - name: CreateBindings
      run:  ./moveAbiBindings.sh 
    - name: Build
      run: cargo build --all
